name: hello-world

on: push

jobs:
  my-job:
    runs-on: macos-latest

    steps:
      - name: Install
        run: brew install chezmoi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Apply
        run: chezmoi apply

      # - name: Tests
      #   run: |
      #     bats tests/*
