name: hello-world

on: push

jobs:
  my-job:
    runs-on: macos-latest

    steps:
      - name: my-step
        run: echo "hello world!"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ChezMoi
        run: |
          which brew
          brew install chezmoi
          which chezmoi

      - name: ChezMoi apply
        run: |
          which brew
          which chezmoi
          chezmoi apply

      - name: Tests
        run: |
          bats tests/*
